version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    groups:
      github-actions:
        patterns:
          - "*"
    cooldown:
      default-days: 30

  - package-ecosystem: uv
    directory: /
    schedule:
      interval: monthly
    groups:
      cdk-dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 30
    commit-message:
      prefix: "chore(cdk)"

  - package-ecosystem: uv
    directory: /cdk/runtimes/eoapi/raster
    schedule:
      interval: monthly
    groups:
      raster-dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 30
    commit-message:
      prefix: "chore(raster)"

  - package-ecosystem: uv
    directory: /cdk/runtimes/eoapi/stac
    schedule:
      interval: monthly
    groups:
      stac-dependencies:
        patterns:
          - "*"
    cooldown:
      default-days: 30
    commit-message:
      prefix: "chore(stac-api)"
