FROM node:lts-alpine AS build
ARG STAC_BROWSER_REPO_TAG=v5.1.0
ARG DYNAMIC_CONFIG=true

RUN apk add --no-cache git
WORKDIR /app
RUN git clone --depth 1 --branch "$STAC_BROWSER_REPO_TAG" https://github.com/radiantearth/stac-browser.git .
COPY cdk/stac_browser_user_config.js ./stac_browser_user_config.js
RUN npm install
ENV DYNAMIC_CONFIG="$DYNAMIC_CONFIG" \
    SB_CONFIG=./stac_browser_user_config.js
RUN [ "$DYNAMIC_CONFIG" = "true" ] && sed -i 's/<!--RC//;s/RC-->//' index.html
RUN npm run build

FROM nginxinc/nginx-unprivileged:1-alpine

USER root
RUN apk add --no-cache jq pcre-tools
COPY --from=build /app/config.schema.json /etc/nginx/conf.d/config.schema.json
COPY --from=build /app/dist /usr/share/nginx/html
COPY --from=build /app/docker/default.conf /etc/nginx/conf.d/default.conf.template
COPY --from=build /app/docker/docker-entrypoint.sh /docker-entrypoint.d/40-stac-browser-entrypoint.sh
RUN rm -f /etc/nginx/conf.d/default.conf && \
    chown -R nginx:nginx /usr/share/nginx/html && \
    chmod +x /docker-entrypoint.d/40-stac-browser-entrypoint.sh

ENV SB_pathPrefix=/
EXPOSE 8080
USER nginx
