import fnmatch
import json
import logging
import re
from collections.abc import Generator
from datetime import UTC, datetime
from typing import Any
from urllib.parse import urlparse

import obstore
import pystac
from obstore.store import from_url
from pystac import Asset, Link
from pystac.extensions.maap_dps import MaapDpsExtension
from pystac.stac_io import DefaultStacIO, StacIO
from slugify import slugify
from stac_pydantic.item import Item

logger = logging.getLogger()
logger.setLevel(logging.INFO)

COLLECTION_ID_FORMAT = "{username}__{algorithm_name}__{algorithm_version}"


def user_catalog_id(username: str) -> str:
    """Return a stable, readable catalog ID for a DPS username."""
    return f"user-{slugify(username, regex_pattern=r'[/\?#%& ]+')}"


def generated_collection_id(job_metadata: dict[str, str]) -> str:
    """Return the existing deterministic DPS collection ID."""
    return slugify(
        COLLECTION_ID_FORMAT.format(**job_metadata), regex_pattern=r"[/\?#%& ]+"
    )


def _generated_catalog(username: str) -> dict[str, Any]:
    return {
        "type": "Catalog",
        "stac_version": "1.1.0",
        "id": user_catalog_id(username),
        "title": f"{username} DPS Outputs",
        "description": f"DPS output collections generated for {username}.",
        "parent_ids": [],
        "links": [],
    }


def _generated_collection(
    collection_id: str, username: str, job_metadata: dict[str, str], user_catalog: str
) -> dict[str, Any]:
    return {
        "type": "Collection",
        "stac_version": "1.1.0",
        "id": collection_id,
        "title": (
            f"{job_metadata['algorithm_name']} "
            f"{job_metadata['algorithm_version']} outputs"
        ),
        "description": (
            f"DPS outputs generated by {job_metadata['algorithm_name']} "
            f"({job_metadata['algorithm_version']}) for {username}."
        ),
        "license": "proprietary",
        "extent": {
            "spatial": {"bbox": [[-180.0, -90.0, 180.0, 90.0]]},
            "temporal": {"interval": [[None, None]]},
        },
        "parent_ids": [user_catalog],
        "links": [],
    }


def _source_collection(
    source: pystac.Collection, collection_id: str, user_catalog: str
) -> dict[str, Any]:
    """Copy source Collection metadata with fresh generated identity links."""
    collection = source.clone()
    collection.make_asset_hrefs_absolute()
    document = collection.to_dict(include_self_link=False)
    document["id"] = collection_id
    document["parent_ids"] = [user_catalog]
    document["links"] = [
        link
        for link in document["links"]
        if link.get("rel")
        not in {
            "self",
            "root",
            "parent",
            "child",
            "item",
            "collection",
            "alternate",
        }
    ]
    return document


class ObstoreStacIO(DefaultStacIO):
    def read_text(self, source: str | Link, *args: Any, **kwargs: Any) -> str:
        parsed = urlparse(str(source))
        key = parsed.path[1:]
        store = from_url(f"{parsed.scheme}://{parsed.netloc}")

        obj = obstore.get(store, key)
        return obj.bytes().to_bytes().decode("utf-8")

    def write_text(self, dest: str | Link, txt: str, *args: Any, **kwargs: Any) -> None:
        parsed = urlparse(str(dest))
        key = parsed.path[1:]
        store = from_url(f"{parsed.scheme}://{parsed.netloc}")
        obstore.put(store, key, bytes(txt, "utf-8"))


StacIO.set_default(ObstoreStacIO)


def get_dps_output_prefix(s3_key) -> str | None:
    """
    Find the S3 key prefix for the outputs associated with a DPS job

    Args:
        s3_key (str): Full S3 key

    Returns:
        str: Path prefix including timestamp, or None if not found
    """
    parsed = urlparse(s3_key)
    path = parsed.path.lstrip("/")

    timestamp_pattern = r"(\d{4}/\d{2}/\d{2}/\d{2}/\d{2}/\d{2}/\d+)"
    match = re.search(timestamp_pattern, path)

    if match:
        end_pos = match.end()
        return path[:end_pos] + "/"

    return None


def load_met_json(
    bucket: str, job_output_prefix: str
) -> tuple[dict[str, str], str] | None:
    """Load DPS metadata and return its discovered object key."""
    store = from_url(f"s3://{bucket}/{job_output_prefix}")
    stream = obstore.list(store, chunk_size=10)
    for list_result in stream:
        for result in list_result:
            met_json_key = result["path"]
            if met_json_key.endswith("met.json"):
                return (
                    json.loads(
                        obstore.get(store, met_json_key)
                        .bytes()
                        .to_bytes()
                        .decode("utf-8")
                    ),
                    met_json_key,
                )
    return None


def is_authorized(
    username: str,
    collection_id: str,
    registry: dict[str, list[str]],
) -> bool:
    """Return True if username is authorized to publish to collection_id.

    Each key in registry is a collection ID pattern (exact string or glob
    wildcard using fnmatch syntax). A user is authorized when their username
    appears in the list for any pattern that matches collection_id.

    Args:
        username: The DPS job submitter's username.
        collection_id: The collection ID the item declares.
        registry: Mapping of collection ID patterns to authorized usernames.

    Returns:
        True if the username is authorized for the given collection ID.
    """
    for pattern, authorized_users in registry.items():
        if fnmatch.fnmatch(collection_id, pattern) and username in authorized_users:
            return True
    return False


def get_stac_documents(
    catalog_json_key: str,
    collection_id_registry: dict[str, list[str]] | None = None,
) -> Generator[Item | dict[str, Any], Any, Any]:
    """Yield generated Catalog, Collection, and Item JSON documents.

    Authorized named collections yield Items only. Generated collections yield a
    user Catalog and one Collection before their Items. A single source Collection
    in the input hierarchy is copied with fresh generated identity; otherwise a
    conservative default Collection is used.
    """
    registry = collection_id_registry or {}

    job_output_prefix = get_dps_output_prefix(catalog_json_key)
    if not job_output_prefix:
        raise ValueError(
            f"could not identify the DPS output prefix from {catalog_json_key}"
        )

    s3_key_parsed = urlparse(catalog_json_key)
    met_json = load_met_json(s3_key_parsed.netloc, job_output_prefix)
    if not met_json:
        raise ValueError(
            "could not locate the .met.json file "
            f"with the DPS job outputs in {job_output_prefix}"
        )

    job_metadata, met_json_key = met_json
    deterministic_collection_id = generated_collection_id(job_metadata)
    username = job_metadata.get("username", "")
    met_json_href = f"s3://{s3_key_parsed.netloc}/{met_json_key.lstrip('/')}"
    processing_time = datetime.now(UTC).isoformat().replace("+00:00", "Z")

    catalog = pystac.Catalog.from_file(catalog_json_key)
    catalog.make_all_asset_hrefs_absolute()

    items: list[tuple[Item, bool]] = []
    generated_source_collection_ids: set[str] = set()
    for item in catalog.get_all_items():
        item_collection_id = item.collection_id
        generated = not (
            item_collection_id and is_authorized(username, item_collection_id, registry)
        )
        if generated:
            item.collection_id = deterministic_collection_id
            if item_collection_id:
                generated_source_collection_ids.add(item_collection_id)
        else:
            logger.info(
                "Preserving user-specified collection %s for user %s",
                item_collection_id,
                username,
            )

        item.stac_extensions[:] = list(dict.fromkeys(item.stac_extensions))
        MaapDpsExtension.ext(item, add_if_missing=True).apply(
            algorithm_name=job_metadata["algorithm_name"],
            processing_version=job_metadata["algorithm_version"],
            username=job_metadata["username"],
            tag=job_metadata["tag"],
        )
        item.properties["created"] = processing_time
        item.add_asset(
            "dps-metadata",
            Asset(
                href=met_json_href,
                media_type="application/json",
                roles=["metadata"],
                title="DPS job metadata",
            ),
        )
        item.links = [
            link
            for link in item.links
            if not (link.rel == "via" and link.href == met_json_href)
        ]
        items.append((Item(**item.to_dict()), generated))

    if any(generated for _, generated in items):
        user_catalog = user_catalog_id(username)
        source_collections = [
            source_collection
            for source_collection in catalog.get_all_collections()
            if source_collection.id in generated_source_collection_ids
        ]
        yield _generated_catalog(username)
        if (
            len(generated_source_collection_ids) == 1
            and len(source_collections) == 1
        ):
            yield _source_collection(
                source_collections[0], deterministic_collection_id, user_catalog
            )
        else:
            yield _generated_collection(
                deterministic_collection_id, username, job_metadata, user_catalog
            )

    for item, _ in items:
        yield item


def get_stac_items(
    catalog_json_key: str,
    collection_id_registry: dict[str, list[str]] | None = None,
) -> Generator[Item, Any, Any]:
    """Yield enriched STAC Items out of a catalog.json.

    Authorized named collections remain Item-only. Use :func:`get_stac_documents`
    when the publishing workflow also needs generated hierarchy documents.
    """
    yield from (
        document
        for document in get_stac_documents(catalog_json_key, collection_id_registry)
        if isinstance(document, Item)
    )
